language: node_js
node_js:
- '12'
branches:
  only:
  - main
cache:
  directories:
  - node_modules
before_install:
- npm update
install:
- npm install
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: NrmkfQSc/7psK1YD8vdhbrdf/XUxzX5jGzF+z7sWW00aM/RfAenyZdyHvauFN3QSYoF0XEj2OepwMcu/mErIRK2h0qLlYVtsdB+G0wQIsXR8mBLjWvTjQyKJRzVc4KeuSJhJku7J8lw6m0PV0YCZ/1bo7kqu5zDgfDRO/en1kJEa/LxbfaoMlgW6K+NcicW1c85MISkvzV3zhzgD7LtqT3+SznhFH0UdRd1Dap1rW36ITBSCG+n8PPfACob3uVhs8cH4sxf0E0QmdxcUSf5+wnnRoG7jhE8TLq1zs3nRdr48o1rw6ZPquB+EgcG70yKfp1WmN0tNymbCoQbSbr7bPUlbvmpVz4l9DTFQmbnRpTwIlHUgXwLaeeFfEQ2do7pktWzDmP6wk7iaWt4YPD0t6uj18/eUnar8JgUGNp++drg1Tsk0KItM9woDb8qrUvUL1lydngbSpAUgKLL5mFhaO8aaKpdxwaD283ce3nqBXzJwt0ffM/zKJUSFiv7F8Ov9AsaYS59Fh34qK+5UYHbTKpRI+DugYc42xOU2TKWSHfwY98uHOC72NtzyzZMwbWXIYJcVir9K05v04jGbxfwaoNzTIrslS2VD+6JdNSTsm7k8D+vuYhUF0tKjXa8UxkGIl1zLq+H4NeQgnYn0zcywBkFOkmlq6eQNjLMOLwgJ/io=
  on: main
  app: g07-backend
